### PR TITLE
error messages are displayed

### LINKED ISSUE #240: 🐛 [Bug] Create user error not caught
## :bug: Bugreport

When creating a user and you filled in all fields the signup button appears (this is not good)
When clicking signup you are for sure redirected to the thanks page(?). If the create user call fails this behaviour is happening anyway. Therefor the user is thanked and gets the impression that everything is alright, while its not.

### PR DESCRIPTION
**Pull request by ogerly**
## 🍰 Pullrequest
error messages are displayed
the error transferred from the backend is displayed 1:1 in the error field. 

### Issues
- fixes #240 
 
FireShot Capture 369 - Gradido Account - localhost

FireShot Capture 372 - Gradido Account - localhost

### CODE REVIEW

File: frontend/src/views/Pages/Register.vue [hunk 1]
```diff
@@ -160,6 +174,8 @@ export default {
       checkPassword: '',
       passwordVisible: false,
       submitted: false,
+      registerfail: false,
```
Comment (ulfgebhardt) [inline frontend/src/views/Pages/Register.vue:177]: Can we rename this field into something more meaningful like `showError` or `errorAlertvisible` please?

**Review by ulfgebhardt — CHANGES_REQUESTED** [review]

File: frontend/src/views/Pages/Register.vue (hunk 1 above)
Comment (ogerly) [reply frontend/src/views/Pages/Register.vue:177]: erledigt

Comment (ulfgebhardt) [reply frontend/src/views/Pages/Register.vue:177]: Lügen!

**Review by einhornimmond — APPROVED** [review]
