### PR TITLE
fix: No Creations for Deleted Users

### LINKED ISSUE #1509: 🚀 [Feature] Disallow creation for deleted Accounts
## 🚀 Feature

While this might be already implemented in #1504 we should warn the admin when trying to create GDD for an disabled account.

Creating GDD for disabled accounts must be impossible

Scenario:
- Admin starts creation
- Other Admin disables account
- Admin confirms creation

### PR DESCRIPTION
**Pull request by Mogge**
## 🍰 Pullrequest
Checks that the user is not deleted when confirming a creation.

### Issues
- fixes #1509 

### Todo

- [X] None

### CODE REVIEW

File: backend/src/graphql/resolver/AdminResolver.ts [hunk 1]
```diff
@@ -263,7 +263,7 @@ export class AdminResolver {
 
     const userIds = pendingCreations.map((p) => p.userId)
     const userCreations = await getUserCreations(userIds)
-    const users = await User.find({ id: In(userIds) })
+    const users = await User.find({ where: { id: In(userIds) }, withDeleted: true })
```
Comment (Mogge) [inline backend/src/graphql/resolver/AdminResolver.ts:266]: When we not collect the deleted users as well, the UI shows empty name, email, etc.

**Review by ulfgebhardt — APPROVED** [review]
