### PR TITLE
fix(backend): subscription get's email and languages from user

### LINKED ISSUE #2711: 🐛 [Bug] Unsubscribe KlickTipp can send email of another user
## 🐛 Bugreport

If a user has a gradido account he can login in graphql and send an unsubscribe("not@me.email") and get a success even if "not@me.email" is not in he user contact.

## TODO
- [ ] Remove the parameter email of the unsubscribe mutation
- [ ] Take the context and call the klickTipp with the email of the contact

### LINKED ISSUE #2785: 🔧 [Refactor] Klicktipp Resolver remove email dependency + create events
## 🔧 Refactor ticket

Klicktipp Resolver remove email dependency and create events

Currently the klicktipp resolver is based on the email not the user - this must be changed due to security issues
- https://github.com/gradido/gradido/issues/2711
- create event for subscribe and unsubscribe #2886

### PR DESCRIPTION
**Pull request by Elweyn**
### Issues

- relates #2785
- fixes #2711

### Todo

- [X] None

### CODE REVIEW

File: backend/src/graphql/resolver/KlicktippResolver.ts [hunk 1]
```diff
@@ -27,15 +26,15 @@ export class KlicktippResolver {
...
 
   @Authorized([RIGHTS.SUBSCRIBE_NEWSLETTER])
   @Mutation(() => Boolean)
-  async subscribeNewsletter(
-    @Args() { email, language }: SubscribeNewsletterArgs,
-  ): Promise<boolean> {
-    return await klicktippSignIn(email, language)
+  async subscribeNewsletter(@Ctx() context: Context): Promise<boolean> {
+    const user = getUser(context)
+    return await klicktippSignIn(user.emailContact.email, user.language)
```
Comment (ulfgebhardt) [inline backend/src/graphql/resolver/KlicktippResolver.ts:38]:
```suggestion
    const user = getUser(context)
    return klicktippSignIn(user.emailContact.email, user.language)
```

File: frontend/src/components/UserSettings/UserNewsletter.vue [hunk 2]
```diff
@@ -41,10 +41,6 @@ export default {
       this.$apollo
         .mutate({
           mutation: this.newsletterState ? subscribeNewsletter : unsubscribeNewsletter,
-          variables: {
-            email: this.$store.state.email,
```
Comment (ulfgebhardt) [inline frontend/src/components/UserSettings/UserNewsletter.vue:45]: do we still need $store.state.email now?

**Review by ulfgebhardt — APPROVED** [review]

File: frontend/src/components/UserSettings/UserNewsletter.vue (hunk 2 above)
Comment (Elweyn) [reply frontend/src/components/UserSettings/UserNewsletter.vue:45]: https://github.com/gradido/gradido/issues/2895
