### PR TITLE
[Fix] Add createdAt & contributionDate to ContributionListItems

### LINKED ISSUE #2089: 🐛 [Bug] Wrong date display of confirmed contribution
## 🐛 [Bug] Bugreport

@Mogge Seeding is fine now; but now we still have a logic problem I think:
In my list we show only one date; the date when the contribution has been deleted, has been confirmed or the contributionDate in case it is still open!
I think that we want both information if not confirmed yet the contributionDate, when deleted the contributionDate and the deletedAt date and last but not least if confirmed the contributionDate and the confirmedAt date

_Originally posted by @Elweyn in https://github.com/gradido/gradido/issues/2083#issuecomment-1195265937_

### PR DESCRIPTION
**Pull request by Elweyn**
## 🍰 Pullrequest

ContributionListItems are ordered by createdAt so we want to see it and the contributionDate

### Issues

- fixes #2089 

### Todo

- [X] Add contributionDate to ContributionListItem

### CODE REVIEW

File: frontend/src/components/Contributions/ContributionListItem.vue [hunk 1]
```diff
@@ -11,6 +11,13 @@
           {{ $t('math.minus') }}
           <div class="mx-2">{{ $d(new Date(date), 'short') }}</div>
         </div>
+        <div class="mr-2">
+          <span>{{ $t('contribution.date') }}</span>
+          <span>
+            {{ $d(new Date(contributionDate), 'month') }}
+            {{ $d(new Date(contributionDate), 'year') }}
```
Comment (Mogge) [inline frontend/src/components/Contributions/ContributionListItem.vue:18]:
```suggestion
            {{ $d(new Date(contributionDate), 'monthAndYear') }}
```

File: frontend/src/components/Contributions/ContributionListItem.spec.js [hunk 2]
```diff
@@ -85,20 +86,8 @@ describe('ContributionListItem', () => {
     })
 
     describe('contribution date', () => {
```
Comment (Mogge) [inline frontend/src/components/Contributions/ContributionListItem.spec.js:88]:
```suggestion
    describe('date', () => {
```

**Review by Mogge — CHANGES_REQUESTED** [review]
Some little things

**Review by Mogge — APPROVED** [review]
