### PR TITLE
233-Support-Button fix, and col error fix

### LINKED ISSUE #233: 🚀 [Feature] Support Button
## :rocket: Feature

Support Button:

We have a support "hotline", we should advertise it:
- In the footer
- In the header (as help button)
- On errors

How does the user contact the support? email?
Do we advertise the email?

### PR DESCRIPTION
**Pull request by ogerly**
## 🍰 Pullrequest
Support link im footer eingebaut, der link verlässt momentan die app
- fehler gefixt .. "col" error

### Issues
- fixes #233 
FireShot Capture 389 - Gradido Account - localhost

### CODE REVIEW

File: frontend/src/views/Layout/ContentFooter.vue [hunk 1]
```diff
@@ -39,6 +39,17 @@
           >
             {{ $t('whitepaper') }}
           </b-nav-item>
+          <b-nav-item
+            :href="
+              $i18n.locale === 'de'
+                ? 'https://gradido.net/de/contact/'
+                : 'https://gradido.net/en/contact/'
```
Comment (ulfgebhardt) [inline frontend/src/views/Layout/ContentFooter.vue:46]: This does not support more then 2 languages - we should refactor this. This link should be part of the language file.

**Review by ulfgebhardt — CHANGES_REQUESTED** [review]

File: frontend/src/views/Layout/ContentFooter.vue (hunk 1 above)
Comment (ogerly) [reply frontend/src/views/Layout/ContentFooter.vue]: geändert

**Review by ulfgebhardt — APPROVED** [review]

**Review by Mogge — APPROVED** [review]

**Review by Mogge — CHANGES_REQUESTED** [review]
Please add `target="_blank"` to Gradidio-Akademie.
Please add a test for the presence of the Support link.

**Review by Mogge — APPROVED** [review]
