### PR TITLE
Fix: Logrotate & Log Dates & Save Update Log & Correct tag Checkout

### LINKED ISSUE #1403: 🐛 [Bug] start.sh allow correct checkout of tags (own branch) + define brach/tag in config
## 🐛 Bugreport

`start.sh` allow correct checkout of tags (own branch) - currently checking out a tag will land you on a detached head. Not bad, but could be better.

Define brach/tag in config - when using `start.sh` it will always check out the `master` when there is no argument to the command. This is dangerous for production, since we want a stable tag checked out there always and explicitly change it on a new deploy. Use the config to set a specific tag/branch

### LINKED ISSUE #1452: 🐛 [Bug] Deployment log files need a date
## 🐛 Bugreport

Deployment log files need a date:

image

### LINKED ISSUE #1453: 🚀 [Feature] Deployment: Log for Update Process
## 🚀 Feature

Deployment: Have logs for the update process.

This includes the output for the HTML visible to the user and the console log not visible to the user

### PR DESCRIPTION
**Pull request by ulfgebhardt**
## 🍰 Pullrequest

- Only rotate logfile, not already rotated files.
- dates in logfile names
- save update log
- fixed bug with module aliases when running the compiled files

### Issues

- fixes #1452 
- fixes #1453 
- fixes #1403 

### Todo

- [X] None

### CODE REVIEW

File: deployment/bare_metal/start.sh [hunk 1]
```diff
@@ -113,11 +121,11 @@ yarn build
 # TODO maybe handle this differently?
 export NODE_ENV=production
 pm2 delete gradido-backend
-pm2 start --name gradido-backend "yarn --cwd $PROJECT_ROOT/backend start" -l $GRADIDO_LOG_PATH/pm2.backend.log --log-date-format 'DD-MM HH:mm:ss.SSS'
+pm2 start --name gradido-backend "yarn --cwd $PROJECT_ROOT/backend start" -l $GRADIDO_LOG_PATH/pm2.backend.$TODAY.log --log-date-format 'DD-MM HH:mm:ss.SSS'
```
Comment (Mogge) [inline deployment/bare_metal/start.sh:124]:
```suggestion
pm2 start --name gradido-backend "yarn --cwd $PROJECT_ROOT/backend start" -l $GRADIDO_LOG_PATH/pm2.backend.$TODAY.log --log-date-format 'YYYY-MM-DD:mm:ss.SSS'
```

File: deployment/bare_metal/start.sh [hunk 2]
```diff
@@ -126,11 +134,11 @@ yarn build
 # TODO maybe handle this differently?
 export NODE_ENV=production
 pm2 delete gradido-frontend
-pm2 start --name gradido-frontend "yarn --cwd $PROJECT_ROOT/frontend start" -l $GRADIDO_LOG_PATH/pm2.frontend.log --log-date-format 'DD-MM HH:mm:ss.SSS'
+pm2 start --name gradido-frontend "yarn --cwd $PROJECT_ROOT/frontend start" -l $GRADIDO_LOG_PATH/pm2.frontend.$TODAY.log --log-date-format 'DD-MM HH:mm:ss.SSS'
```
Comment (Mogge) [inline deployment/bare_metal/start.sh:137]:
```suggestion
pm2 start --name gradido-frontend "yarn --cwd $PROJECT_ROOT/frontend start" -l $GRADIDO_LOG_PATH/pm2.frontend.$TODAY.log --log-date-format 'YYYY-MM-DD HH:mm:ss.SSS'
```

File: deployment/bare_metal/start.sh [hunk 3]
```diff
@@ -139,14 +147,17 @@ yarn build
 # TODO maybe handle this differently?
 export NODE_ENV=production
 pm2 delete gradido-admin
-pm2 start --name gradido-admin "yarn --cwd $PROJECT_ROOT/admin start" -l $GRADIDO_LOG_PATH/pm2.admin.log --log-date-format 'DD-MM HH:mm:ss.SSS'
+pm2 start --name gradido-admin "yarn --cwd $PROJECT_ROOT/admin start" -l $GRADIDO_LOG_PATH/pm2.admin.$TODAY.log --log-date-format 'DD-MM HH:mm:ss.SSS'
```
Comment (Mogge) [inline deployment/bare_metal/start.sh:150]:
```suggestion
pm2 start --name gradido-admin "yarn --cwd $PROJECT_ROOT/admin start" -l $GRADIDO_LOG_PATH/pm2.admin.$TODAY.log --log-date-format 'YYYY-MM-DD HH:mm:ss.SSS'
```

**Review by Mogge — CHANGES_REQUESTED** [review]

File: deployment/bare_metal/start.sh [hunk 4]
```diff
@@ -113,11 +121,11 @@ yarn build
 # TODO maybe handle this differently?
 export NODE_ENV=production
 pm2 delete gradido-backend
-pm2 start --name gradido-backend "yarn --cwd $PROJECT_ROOT/backend start" -l $GRADIDO_LOG_PATH/pm2.backend.log --log-date-format 'DD-MM HH:mm:ss.SSS'
+pm2 start --name gradido-backend "yarn --cwd $PROJECT_ROOT/backend start" -l $GRADIDO_LOG_PATH/pm2.backend.$TODAY.log --log-date-format 'YYYY-MM-DD:mm:ss.SSS'
```
Comment (Mogge) [inline deployment/bare_metal/start.sh:124]:
```suggestion
pm2 start --name gradido-backend "yarn --cwd $PROJECT_ROOT/backend start" -l $GRADIDO_LOG_PATH/pm2.backend.$TODAY.log --log-date-format 'YYYY-MM-DD HH:mm:ss.SSS'
```

**Review by Mogge — APPROVED** [review]

**Review by Mogge — APPROVED** [review]
