### PR TITLE
fix: 🐛 Prevent Loosing Redeem Code When Changing Between Register and Login in Auth Navbar

### LINKED ISSUE #2246: 🐛 [Bug] Redeem Code is Lost
## 🐛 Bugreport
 * have a valid transaction link
 * logout
 * use the transaction link
 * when on login page, click on register on the top
 * see that the redeem code is lost

The redeem code must not be lost when changing between register and login on the top buttons

### PR DESCRIPTION
**Pull request by mahula**
### Issues
- fixes #2246

### Todo
- [X] use computed links to cover links containing redeem codes
- [x] use the computed properties as mixins in components `AuthNavbar`, `AuthNavbarSmall`, and `Redeem LoggedOut`

### CODE REVIEW

File: frontend/src/components/LinkInformations/RedeemLoggedOut.vue [hunk 1]
```diff
@@ -25,23 +25,17 @@
 </template>
 <script>
 import RedeemInformation from '@/components/LinkInformations/RedeemInformation.vue'
+import { authLinks } from '../../mixins/authLinks'
```
Comment (Mogge) [inline frontend/src/components/LinkInformations/RedeemLoggedOut.vue:28]:
```suggestion
import { authLinks } from '@/mixins/authLinks'
```

**Review by Mogge — CHANGES_REQUESTED** [review]
Looks very good. Great work with the mixin. Please avoid relative paths if possible

File: frontend/src/components/LinkInformations/RedeemLoggedOut.vue (hunk 1 above)
Comment (mahula) [reply frontend/src/components/LinkInformations/RedeemLoggedOut.vue]: Sure.
Fixed with https://github.com/gradido/gradido/commit/3439bdc67337f0041719a9a3636dec2a5a16d856.

**Review by Mogge — APPROVED** [review]
