### PR TITLE
fix(database): consistent deleted at bewteen users and user contacts

### LINKED ISSUE #2436: 🐛 [Bug] Data inconsistency - user & user_contacts
## 🐛 Bugreport

Data inconsistency - user & user_contacts

- There is live users with deleted user contacts (when restoring users)
- There is live user contacts with deleted users (on production data 2 occurrences)

`SELECT email FROM users LEFT JOIN user_contacts ON users.email_id = user_contacts.id WHERE users.deleted_at IS NOT NULL AND  user_contacts.deleted_at IS NULL;`

`SELECT email FROM users LEFT JOIN user_contacts ON users.email_id = user_contacts.id WHERE users.deleted_at IS NULL AND  user_contacts.deleted_at IS NOT NULL;`

- [ ] Make sure to fix delete & restore logic for users to include the user contacts
- [ ] Research if we can define an automatisation with typeorm (when marking as deleted on this model also mark as deleted on connected other model)
- [ ] Write migration to ensure consistency of data (undelete user_contacts where needed, delete user_contacts where needed)

### PR DESCRIPTION
**Pull request by Mogge**
### Issues
- fixes #2436

### Todo

- [X] None

### CODE REVIEW

File: database/migrations/0055-consistent_deleted_users.ts [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+    AND user_id IN (SELECT id FROM users WHERE deleted_at IS NOT NULL);`)
+
+  for (let i = 0; i < contactsToFix.length; i++) {
+    const deletedAt = new Date(contactsToFix[i].deleted_at)
+      .toISOString()
+      .slice(0, 19)
+      .replace('T', ' ')
+
+    await queryFn(`
+      UPDATE user_contacts SET deleted_at = '${deletedAt}' WHERE id = ${contactsToFix[i].id};`)
```
Comment (ulfgebhardt) [inline database/migrations/0055-consistent_deleted_users.ts:20]: `UPDATE user_contacts SET uc.deletedAt = u.deletedAt WHERE ....

Also remove the for`
