### PR TITLE
fix(frontend): close all open collapse by change tabs in community

### LINKED ISSUE #2380: 🐛 [Bug] Community tab change must close conversation window
## 🐛 Bugreport

1. open conversation of contribution in frontend
2. edit contribution
3. update only visible after closing and reopening conversation window

image

Suggested solution: Close conversation window when changing tabs/editing etc

### PR DESCRIPTION
**Pull request by ogerly**
## 🍰 Pullrequest
when i change the tab it closes all open tabs from the child elements. 
if i have a message box open within the contribution list and want to open another one, it also closes the open one first.

### Issues
- fixes #2380

### CODE REVIEW

File: frontend/src/components/Contributions/ContributionListItem.vue [hunk 1]
```diff
@@ -54,7 +54,7 @@
                 v-b-toggle="collapsId"
                 icon="chat-dots"
                 class="h2 mr-5"
-                @click="getListContributionMessages"
+                @click="$emit('closeAllOpenCollapse'), getListContributionMessages"
```
Comment (ulfgebhardt) [inline frontend/src/components/Contributions/ContributionListItem.vue:57]: should the emit not be part of `getListContributionMessages`? I am asking because I do not know the correct standards of vue.

**Review by Mogge — APPROVED** [review]
