### PR TITLE
fix(backend): moderation message are completely hidden from the user

### LINKED ISSUE #3120: 🐛 [Bug][Frontend] User see a please respond to question on a moderator message
## 🐛 Bugreport

When a moderator sends a moderator message the user see's a message "please respond to question"

### PR DESCRIPTION
**Pull request by ulfgebhardt**
## 🍰 Pullrequest

moderation message are completely hidden from the user

- do not show "Please respond..."
- do not show moderator chat button

### Issues

- fixes #3120 #3126 

### Todo

- [X] None

### CODE REVIEW

File: backend/src/graphql/resolver/ContributionMessageResolver.ts [hunk 1]
```diff
@@ -158,16 +158,18 @@ export class ContributionMessageResolver {
...
-        contribution.contributionStatus === ContributionStatus.DELETED ||
-        contribution.contributionStatus === ContributionStatus.DENIED ||
-        contribution.contributionStatus === ContributionStatus.PENDING
-      ) {
-        contribution.contributionStatus = ContributionStatus.IN_PROGRESS
-        await queryRunner.manager.update(DbContribution, { id: contributionId }, contribution)
-      }
-
       if (messageType !== ContributionMessageType.MODERATOR) {
+        // change status (does not apply to moderator messages)
```
Comment (Mogge) [inline backend/src/graphql/resolver/ContributionMessageResolver.ts:162]: Good catch. Please add a unit test for this, e.g. test that a moderator message does not change the status

**Review by Mogge — CHANGES_REQUESTED** [review]

File: backend/src/graphql/resolver/ContributionMessageResolver.test.ts [hunk 2]
```diff
@@ -193,53 +200,37 @@ describe('ContributionMessageResolver', () => {
...
-            senderLastName: 'Lustig',
-            contributionMemo: 'Test env contribution',
-          })
+        it("don't call sendAddedContributionMessageEmail", () => {
+          expect(sendAddedContributionMessageEmail).not.toBeCalled()
         })
 
-        it('stores the ADMIN_CONTRIBUTION_MESSAGE_CREATE event in the database', async () => {
-          await expect(DbEvent.find()).resolves.toContainEqual(
+        it("don't change contribution status", async () => {
```
Comment (Mogge) [inline backend/src/graphql/resolver/ContributionMessageResolver.test.ts:207]: single quotes? Is this accepted by the linter?
```suggestion
        it('does not change contribution status", async () => {
```

File: backend/src/graphql/resolver/ContributionMessageResolver.test.ts [hunk 3]
```diff
@@ -193,53 +200,37 @@ describe('ContributionMessageResolver', () => {
...
-          expect(sendAddedContributionMessageEmail).toBeCalledWith({
-            firstName: 'Bibi',
-            lastName: 'Bloxberg',
-            email: 'bibi@bloxberg.de',
-            language: 'de',
-            senderFirstName: 'Peter',
-            senderLastName: 'Lustig',
-            contributionMemo: 'Test env contribution',
-          })
+        it("don't call sendAddedContributionMessageEmail", () => {
```
Comment (Mogge) [inline backend/src/graphql/resolver/ContributionMessageResolver.test.ts:203]:
```suggestion
        it('does not call sendAddedContributionMessageEmail", () => {
```

**Review by Mogge — CHANGES_REQUESTED** [review]

**Review by Mogge — APPROVED** [review]
