### PR TITLE
fix(database): consistent transaction table

### LINKED ISSUE #2430: 🔧 [Refactor] Transaction Table inconsistent
## 🔧 Refactor ticket

Transaction Table inconsistent

There is transactions with user_ids which do not exist in the user table.

- [ ] Create a migration to create those users with the corresponding ids and `unknown` or `anonymous` as names etc.

### PR DESCRIPTION
**Pull request by Mogge**
## 🍰 Pullrequest
Creates the missing users that were deleted though having a transaction

### Issues
- fixes #2430 

### Todo

- [X] None

### CODE REVIEW

File: database/migrations/0056-consistent_transactions_table.ts [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+      )
+    } while (countIds[0] > 0)
+
+    const userContact = await queryFn(`
+      INSERT INTO user_contacts
+      (type, user_id, email, email_checked, created_at, deleted_at)
+      VALUES
+      ('EMAIL', ${missingUserIds[i].user_id}, 'deleted.user${missingUserIds[i].user_id}@gradido.net', 0, NOW(), NOW());`)
+
+    const emaiId = Object.values(userContact)[Object.keys(userContact).indexOf('insertId')]
```
Comment (ulfgebhardt) [inline database/migrations/0056-consistent_transactions_table.ts:28]: why is this construct so complicated?

cant we do `userContact[0].insertId`?

**Review by ulfgebhardt — APPROVED** [review]
@Mogge https://github.com/gradido/gradido/pull/2453/commits/97b169da2e701bf4dfed931ad3c53c1b0da2d3c3
