### PR TITLE
devops: Disable DB Reset on Stage 1

### LINKED ISSUE #1829: 🐛 [Bug] Problem on stage1 with seed data reset
## 🐛 Bugreport

```
$ cross-env TZ=UTC ts-node src/index.ts reset
Error: ER_DUP_FIELDNAME: Duplicate column name 'login_user_id'
    at Query.Sequence._packetToError (/home/gradido/gradido/database/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/home/gradido/gradido/database/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/home/gradido/gradido/database/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/gradido/gradido/database/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/gradido/gradido/database/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/gradido/gradido/database/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/gradido/gradido/database/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/gradido/gradido/database/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (/home/gradido/gradido/database/node_modules/mysql/lib/Pool.js:199:23)
    at node:internal/util:360:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (node:internal/util:346:12)
    at Migration.query (/home/gradido/gradido/database/node_modules/ts-mysql-migrate/src/migrations.ts:283:12)
    at Object.<anonymous> (/home/gradido/gradido/database/migrations/0019-replace_login_user_id_with_state_user_id.ts:31:9)
    at Generator.next (<anonymous>)
    at /home/gradido/gradido/database/migrations/0019-replace_login_user_id_with_state_user_id.ts:14:71
    at new Promise (<anonymous>)
    at __awaiter (/home/gradido/gradido/database/migrations/0019-replace_login_user_id_with_state_user_id.ts:10:12) {
  code: 'ER_DUP_FIELDNAME',
  errno: 1060,
  sqlMessage: "Duplicate column name 'login_user_id'",
  sqlState: '42S21',
  index: 0,
  sql: 'ALTER TABLE `state_users` ADD COLUMN `login_user_id` int(10) unsigned DEFAULT NULL AFTER `id`;'
}
error Command failed with exit code 1.
```

This only happens on the seed data stuff

Current "solution":
```
sudo mysql -u root
drop database gradido_community;
```

Maybe this is obsolete with the new seed

### PR DESCRIPTION
**Pull request by Mogge**
## 🍰 Pullrequest
dito

### Issues
- fixes #1829

### Todo

- [X] None

### CODE REVIEW

**Review by ulfgebhardt — APPROVED** [review]

File: deployment/bare_metal/start.sh [hunk 1]
```diff
@@ -105,7 +105,8 @@ yarn install
 yarn build
 if [ "$DEPLOY_SEED_DATA" = "true" ]; then
   yarn dev_up
-  yarn dev_reset
+# As de_reset is not running properly (0019-replace_login_user_id_with_state_user_id)
```
Comment (Mogge) [inline deployment/bare_metal/start.sh:108]:
```suggestion
# As dev_reset is not running properly (0019-replace_login_user_id_with_state_user_id)  
```
