### PR TITLE
fix(admin): update contribution list after admin updates contribution

### LINKED ISSUE #2097: 🐛 [Bug] Update Admin Contribution Does not Update in List
## 🐛 Bugreport
 * Create an admin contribution
 * Edit the contribution memo text
 * Save
 
The Memo text does not update in the open contribution list.

### PR DESCRIPTION
**Pull request by Mogge**
## 🍰 Pullrequest

This not only fixes the bug, but also uses apollo to fetch data on creation as it should be done everywhere, including unit tests with mock apollo client

### Issues
- fixes #2097 
- relates #1872 

### Todo

- [X] None

### CODE REVIEW

File: admin/src/pages/CreationConfirm.vue [hunk 1]
```diff
@@ -71,21 +72,6 @@ export default {
           this.toastError(error.message)
         })
     },
```
Comment (ulfgebhardt) [inline admin/src/pages/CreationConfirm.vue:74]: whats with `confirmCreation`? Why can this mutation not live in the `apollo` field? Can we not annotate the corresponding button aswell?

**Review by ulfgebhardt — COMMENTED** [review]
All good, but what about the mutation still in old style?

File: admin/src/pages/CreationConfirm.vue (hunk 1 above)
Comment (Mogge) [reply admin/src/pages/CreationConfirm.vue:74]: Docu says: Use `this.$apollo.mutate()` to send a GraphQL mutation.
See: https://apollo.vuejs.org/guide/apollo/mutations.html
I think we use it correctly

**Review by ulfgebhardt — APPROVED** [review]
