### PR TITLE
fix(frontend): leaves are over the user symbol

### LINKED ISSUE #2513: 🐛 [Bug] [Design] Leaves are over the user symbol
## 🐛 Bugreport

Leaves are over the user symbol covering it:
image

### PR DESCRIPTION
**Pull request by ogerly**
## 🍰 Pullrequest
leaves are over the user symbol

### Issues
- fixes #2513

 
Bildschirmfoto vom 2023-01-09 11-41-39

### CODE REVIEW

File: frontend/src/layouts/DashboardLayout.vue [hunk 1]
```diff
@@ -177,7 +177,7 @@ export default {
           } = result
           this.GdtBalance =
             transactionList.balance.balanceGDT === null
-              ? null
+              ? 0
```
Comment (Mogge) [inline frontend/src/layouts/DashboardLayout.vue:180]: Do we really want this? If for some reason the GDT server is not working. this may confuse the users a lot. `null` renders as `-`

**Review by Mogge — DISMISSED** [review]

File: frontend/src/layouts/DashboardLayout.vue (hunk 1 above)
Comment (ogerly) [reply frontend/src/layouts/DashboardLayout.vue:180]: then we must test this times through what really happens if the GDT server times really does not go. I had yesterday the case that the GDT server did not go and **null** was detected as an error. 
I have but later noticed. so I have changed this to **0**. I change this back again.

**Review by ulfgebhardt — APPROVED** [review]
